import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NIKHIL GOYAL
 */
public class ContactUs extends javax.swing.JFrame {

    /**
     * Creates new form ContactUs
     */
    public ContactUs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CLOSE1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textpanel = new javax.swing.JTextPane();
        SUBMIT = new javax.swing.JButton();
        BOOKINGPAGE = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("                   GOYAL'S HOTEL");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 1100));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("    WELCOME TO OUR GOYAL'S HOTEL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 140, 819, 56);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("             FOR AND QUERY PLEASE CONTACT TO : Mr. NIKHIL GOYAL (CEO)         ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 700, 955, 62);

        CLOSE1.setBackground(new java.awt.Color(255, 51, 51));
        CLOSE1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CLOSE1.setForeground(new java.awt.Color(157, 67, 67));
        CLOSE1.setText("LOGOUT");
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE1);
        CLOSE1.setBounds(860, 50, 130, 60);

        jButton1.setBackground(new java.awt.Color(32, 238, 111));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("CONTACT US");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 580, 190, 55);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 29, 221));
        jLabel4.setText("Write your Query :- ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 510, 402, 63);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 29, 221));
        jLabel5.setText("Mr. NIKHIL GOYAL {CEO}");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 380, 402, 63);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(100, 29, 221));
        jLabel6.setText("developer.nikhil.goyal@gmail.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 450, 402, 63);

        jScrollPane1.setViewportView(textpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(562, 434, 428, 102);

        SUBMIT.setBackground(new java.awt.Color(0, 0, 255));
        SUBMIT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SUBMIT.setForeground(new java.awt.Color(255, 0, 51));
        SUBMIT.setText("SUBMIT");
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        getContentPane().add(SUBMIT);
        SUBMIT.setBounds(570, 560, 170, 64);

        BOOKINGPAGE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BOOKINGPAGE.setForeground(new java.awt.Color(255, 0, 0));
        BOOKINGPAGE.setText("GOTO BOOKING PAGE");
        BOOKINGPAGE.setBorder(new javax.swing.border.MatteBorder(null));
        BOOKINGPAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKINGPAGEActionPerformed(evt);
            }
        });
        getContentPane().add(BOOKINGPAGE);
        BOOKINGPAGE.setBounds(780, 557, 210, 70);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/N NAME LOGO - netbeans.jpg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(190, 40, 87, 80);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("  GOYAL'S HOTEL");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 40, 580, 80);

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contact_top_img.jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 230, 390, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        int ans=JOptionPane.showConfirmDialog(null, "Do you want to Submit your Query");
        String type=textpanel.getText();
        if(ans==JOptionPane.YES_OPTION)
        {
        if(type.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Type your query");
        } 
        else
        {
            
            JOptionPane.showMessageDialog(null,"Your Query is Submitted Successfull");
            JOptionPane.showMessageDialog(null,"We shall give you reply in before 24 hrs. Thankyou");
        }
        }
        textpanel.setText("");
    }//GEN-LAST:event_SUBMITActionPerformed

    private void BOOKINGPAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKINGPAGEActionPerformed
        BOOKINGPAGE obj=new BOOKINGPAGE();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BOOKINGPAGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactUs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactUs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOKINGPAGE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton SUBMIT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextPane textpanel;
    // End of variables declaration//GEN-END:variables
}
