import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NIKHIL GOYAL
 */
public class LOGINANDSIGNUPPAGE extends javax.swing.JFrame {

    /**
     * Creates new form LOGINANDSIGNUPPAGE
     */
    public LOGINANDSIGNUPPAGE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HOTEL_ID = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        LOGIN = new javax.swing.JButton();
        SIGNUP = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 1100));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("  GOYAL'S HOTEL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 580, 80);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("    WELCOME TO OUR GOYAL'S HOTEL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(91, 129, 819, 56);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 37, 64));
        jLabel3.setText("ENTER YOUR HOTEL ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(123, 259, 271, 58);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 37, 64));
        jLabel4.setText("ENTER YOUR PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(123, 365, 255, 57);

        HOTEL_ID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HOTEL_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOTEL_IDActionPerformed(evt);
            }
        });
        getContentPane().add(HOTEL_ID);
        HOTEL_ID.setBounds(532, 259, 244, 58);

        PASSWORD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD);
        PASSWORD.setBounds(532, 365, 244, 57);

        LOGIN.setBackground(new java.awt.Color(188, 35, 42));
        LOGIN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(119, 28, 28));
        LOGIN.setText("LOGIN");
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN);
        LOGIN.setBounds(535, 508, 112, 53);

        SIGNUP.setBackground(new java.awt.Color(188, 35, 42));
        SIGNUP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SIGNUP.setForeground(new java.awt.Color(119, 28, 28));
        SIGNUP.setText("SIGNUP");
        SIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGNUPActionPerformed(evt);
            }
        });
        getContentPane().add(SIGNUP);
        SIGNUP.setBounds(665, 508, 111, 53);

        CLEAR.setBackground(new java.awt.Color(188, 35, 42));
        CLEAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(119, 28, 28));
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(123, 508, 105, 53);

        CLOSE.setBackground(new java.awt.Color(188, 35, 42));
        CLOSE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CLOSE.setForeground(new java.awt.Color(119, 28, 28));
        CLOSE.setText("CLOSE");
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE);
        CLOSE.setBounds(260, 508, 109, 53);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 11, 142));
        jLabel5.setText("   NOW BOOK YOUR ROOM AT 50 % OFF");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 690, 719, 76);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 42, 149));
        jLabel6.setText("      FOR AND QUERY PLEASE CONTACT TO : Mr. NIKHIL GOYAL (CEO)         ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 630, 729, 42);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/N NAME LOGO - netbeans.jpg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(130, 30, 87, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void SIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGNUPActionPerformed
        SIGNUP obj=new SIGNUP();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SIGNUPActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        HOTEL_ID.setText("");
        PASSWORD.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
    int dn=0;
    String dna="";
    try
    {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/HOTEL","root","");
        Statement stmt=con.createStatement();
        String query="SELECT * from HOTEL where HOTEL_ID="+HOTEL_ID.getText()+" AND PASSWORD='"+PASSWORD.getText()+"';";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next())
        {
            dn=rs.getInt("HOTEL_ID");
            dna=rs.getString("PASSWORD");      
        }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    } 
    if(dn!=0 && dna!="")
    {
        JOptionPane.showMessageDialog(null,"Congratulation , Login Successfull");
        HOTEL_ID.setText("");
        PASSWORD.setText("");
        BOOKINGPAGE obj=new BOOKINGPAGE();
        obj.setVisible(true);
        this.setVisible(false);
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Account Not Found !!!! Try Again");
        HOTEL_ID.setText("Try Again");
        PASSWORD.setText("");
    }      
    }//GEN-LAST:event_LOGINActionPerformed

    private void HOTEL_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOTEL_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOTEL_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINANDSIGNUPPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINANDSIGNUPPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINANDSIGNUPPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINANDSIGNUPPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINANDSIGNUPPAGE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton CLOSE;
    private javax.swing.JTextField HOTEL_ID;
    private javax.swing.JButton LOGIN;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JButton SIGNUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
