import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NIKHIL GOYAL
 */
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BOOKINGPAGE1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        CONFIRM = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ROOMTYPE = new javax.swing.JComboBox<>();
        NAME = new javax.swing.JTextField();
        EMAILID = new javax.swing.JTextField();
        TOTALGUESTS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JPasswordField();
        HOTEL_ID = new javax.swing.JTextField();
        LOGINANDSIGNUPPAGE = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        BOOKINGPAGE1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BOOKINGPAGE1.setForeground(new java.awt.Color(255, 0, 0));
        BOOKINGPAGE1.setText("GOTO BOOKING PAGE");
        BOOKINGPAGE1.setBorder(new javax.swing.border.MatteBorder(null));
        BOOKINGPAGE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKINGPAGE1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 1100));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 16, 48));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 160, 785, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 90, 201));
        jLabel2.setText("    WELCOME TO OUR GOYAL'S HOTEL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 819, 56);

        CLEAR.setBackground(new java.awt.Color(104, 154, 211));
        CLEAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(CLEAR);
        CLEAR.setBounds(601, 742, 119, 53);

        CLOSE.setBackground(new java.awt.Color(221, 46, 46));
        CLOSE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CLOSE.setForeground(new java.awt.Color(153, 51, 255));
        CLOSE.setText("LOGOUT");
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE);
        CLOSE.setBounds(830, 20, 144, 53);

        CONFIRM.setBackground(new java.awt.Color(104, 154, 211));
        CONFIRM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CONFIRM.setText("CONFIRM");
        CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMActionPerformed(evt);
            }
        });
        getContentPane().add(CONFIRM);
        CONFIRM.setBounds(464, 743, 119, 54);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("   NOTE :- PLEASE USE CASE SENSITIVE PASSWORD.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(92, 866, 770, 47);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("          HOTEL BOOKING");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(331, 156, 328, 51);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(92, 415, 174, 43);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("E-MAIL ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(92, 490, 157, 38);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("TOTAL GUESTS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(92, 576, 194, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 255));
        jLabel8.setText("ROOM TYPE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(92, 653, 203, 48);

        ROOMTYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR ROOM TYPE", "SINGLE ROOM FOR ONE PERSON", "SINGLE ROOM FOR TWO PERSON", "FAMILY ROOM" }));
        getContentPane().add(ROOMTYPE);
        ROOMTYPE.setBounds(464, 654, 261, 48);
        getContentPane().add(NAME);
        NAME.setBounds(464, 415, 261, 57);
        getContentPane().add(EMAILID);
        EMAILID.setBounds(464, 490, 261, 60);
        getContentPane().add(TOTALGUESTS);
        TOTALGUESTS.setBounds(464, 568, 261, 58);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("HOTEL ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(92, 249, 202, 54);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("PASSWORD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(92, 325, 184, 57);

        PASSWORD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(PASSWORD);
        PASSWORD.setBounds(464, 326, 261, 57);

        HOTEL_ID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(HOTEL_ID);
        HOTEL_ID.setBounds(464, 248, 261, 59);

        LOGINANDSIGNUPPAGE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LOGINANDSIGNUPPAGE.setForeground(new java.awt.Color(255, 0, 0));
        LOGINANDSIGNUPPAGE.setText("HOMEPAGE");
        LOGINANDSIGNUPPAGE.setBorder(new javax.swing.border.MatteBorder(null));
        LOGINANDSIGNUPPAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINANDSIGNUPPAGEActionPerformed(evt);
            }
        });
        getContentPane().add(LOGINANDSIGNUPPAGE);
        LOGINANDSIGNUPPAGE.setBounds(92, 739, 227, 58);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/N NAME LOGO - netbeans.jpg"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(150, 10, 87, 80);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("  GOYAL'S HOTEL");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(230, 10, 580, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMActionPerformed
    int flag=0;
    try
    {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/HOTEL","root","");
        Statement stmt=con.createStatement();
        String query="insert into HOTEL(HOTEL_ID,PASSWORD,NAME,EMAIL_ID,TOTAL_GUESTS) values ("+HOTEL_ID.getText()+",'"+PASSWORD.getText()+"','"+NAME.getText()+"','"+EMAILID.getText()+"',"+TOTALGUESTS.getText()+");";
        stmt.executeUpdate(query);
        JOptionPane.showMessageDialog(null,"Registered Successfully");
        con.close();
        HOTEL_ID.setText("");
        PASSWORD.setText("");
        NAME.setText("");
        EMAILID.setText("");
        TOTALGUESTS.setText("");
    }
    catch(Exception e)
    {
        flag=1;
        JOptionPane.showMessageDialog(null, e);
    }
    if(flag==0)
    {
        LOGINANDSIGNUPPAGE obj=new LOGINANDSIGNUPPAGE();
        obj.setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_CONFIRMActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
    HOTEL_ID.setText("");
    PASSWORD.setText("");
    NAME.setText("");
    EMAILID.setText("");
    TOTALGUESTS.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void BOOKINGPAGE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKINGPAGE1ActionPerformed
        BOOKINGPAGE obj=new BOOKINGPAGE();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BOOKINGPAGE1ActionPerformed

    private void LOGINANDSIGNUPPAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINANDSIGNUPPAGEActionPerformed
         LOGINANDSIGNUPPAGE obj=new LOGINANDSIGNUPPAGE();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LOGINANDSIGNUPPAGEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOKINGPAGE1;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CONFIRM;
    private javax.swing.JTextField EMAILID;
    private javax.swing.JTextField HOTEL_ID;
    private javax.swing.JButton LOGINANDSIGNUPPAGE;
    private javax.swing.JTextField NAME;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JComboBox<String> ROOMTYPE;
    private javax.swing.JTextField TOTALGUESTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
